x-worker-base: &worker-base
  build: .
  depends_on:
    - temporal
  networks:
    - temporal-network
    - shared-network
  restart: on-failure
  env_file: .env

services:
  temporal:
    image: temporalio/admin-tools:latest
    container_name: temporal-server
    command: [ "temporal", "server", "start-dev", "--ip", "0.0.0.0" ]
    ports:
      - "7233:7233" # Порт для подключения Worker и Client (gRPC)
      - "8233:8233" # Порт для Web UI
    networks:
      - temporal-network

  # 1. Main Worker: Оркестрация (Workflows)
  main-worker:
    <<: *worker-base
    container_name: temporal-main-worker
    command: python -m app.workers.main_worker

  # 2. IO Worker: Работа с БД и внешними API
  io-worker:
    <<: *worker-base
    container_name: temporal-io-worker
    command: python -m app.workers.io_worker
    # Можно ограничить ресурсы, так как IO воркер в основном ждет ответа сети
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'

  # 3. CPU Worker: Тяжелые вычисления (например, обработка фото/видео)
  cpu-worker:
    <<: *worker-base
    container_name: temporal-cpu-worker
    command: python -m app.workers.cpu_worker
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1G'

  # 4. GPU Worker: Тяжелые вычисления (например, работа с моделями)
  gpu-worker:
    <<: *worker-base
    container_name: temporal-gpu-worker
    command: python -m app.workers.gpu_worker
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1G'

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - shared-network
    volumes:
      - ./include/db/migrations:/docker-entrypoint-initdb.d:ro

  wiremock:
    image: wiremock/wiremock:latest
    command: [ "--global-response-templating" ]
    networks:
      - shared-network
    volumes:
      - ./include/wiremock:/home/wiremock

networks:
  temporal-network:
    driver: bridge
  shared-network:
    driver: bridge